//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanofi_GSP_EXPORT {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class compare_form {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal compare_form() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sanofi_GSP_EXPORT.compare_form", typeof(compare_form).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=17,Y=17} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Point statusStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("statusStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=127,Y=17} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Point timer1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool 入库单号_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("入库单号.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool 创建时间_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("创建时间.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool 所在库位号_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("所在库位号.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool 所在货箱号_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("所在货箱号.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool 批号_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("批号.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool 是否上传_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("是否上传.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool 监管码_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("监管码.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool 监管码校验情况_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("监管码校验情况.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool 药监网编号_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("药监网编号.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool 货主_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("货主.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
